name: store_accounting_desktop
description: "نرم‌افزار حسابداری فروشگاهی (نسخه ویندوز) با امکانات حداقلی، هم‌راستا با اپ موبایل صندوق/مدیریت"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir.ttf
        - asset: assets/fonts/Vazir-Bold.ttf
          weight: 700
